/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.FormaPagamentoDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.FormaPagamento;

/**
 *
 * @author Roberto Oliveira
 */
public class ViewPagamentos extends javax.swing.JFrame {

    /**
     * Creates new form ViewPagamentos
     */
    private boolean existeSelecionado = false;

    public ViewPagamentos() {
        initComponents();
        configureLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfDescricao = new javax.swing.JTextField();
        btSalvar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbFormaPagamento = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Código");

        tfCodigo.setEditable(false);

        jLabel2.setText("Descricao");

        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/salvar.png"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/deletar.png"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/limpar.png"))); // NOI18N
        btCancelar.setText("Limpar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        tbFormaPagamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbFormaPagamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbFormaPagamentoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbFormaPagamento);
        if (tbFormaPagamento.getColumnModel().getColumnCount() > 0) {
            tbFormaPagamento.getColumnModel().getColumn(0).setResizable(false);
            tbFormaPagamento.getColumnModel().getColumn(0).setPreferredWidth(20);
            tbFormaPagamento.getColumnModel().getColumn(1).setResizable(false);
            tbFormaPagamento.getColumnModel().getColumn(1).setPreferredWidth(200);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(32, 32, 32)
                            .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(53, 53, 53)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(230, 230, 230))
                                .addComponent(tfDescricao))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar)
                    .addComponent(btExcluir)
                    .addComponent(btCancelar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        // Persistindo uma nova Forma de Pagamento
        FormaPagamentoDAO fpDao = new FormaPagamentoDAO();
        FormaPagamento formaPagamento = new FormaPagamento(tfDescricao.getText());

        // Se existir um registro selecionado: ATUALIZA, senão: CADASTRA
        if (existeSelecionado) {
            formaPagamento.setId(Long.parseLong(tfCodigo.getText()));
            fpDao.update(formaPagamento);
            JOptionPane.showMessageDialog(null, "Forma de Pagamento atualizada com sucesso.");
        } else {
            fpDao.persist(formaPagamento);
            JOptionPane.showMessageDialog(null, "Forma de Pagamento cadastrado com sucesso.");
        }

        clearAll();
        loadTable();
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // Evento para deletar um registro

        // Verificando se existe um registro selecionado
        if (!tfCodigo.getText().equals("")) {
            // Buscando e deletando o registro no banco
            FormaPagamentoDAO fpDao = new FormaPagamentoDAO();
            FormaPagamento formaPagamento = fpDao.findById(Long.parseLong(tfCodigo.getText()));

            if (formaPagamento == null) {
                JOptionPane.showMessageDialog(null, "Forma de pagamento não encontrada.");
            } else {
                fpDao.remove(formaPagamento);
                JOptionPane.showMessageDialog(null, "A Forma de Pagamento" + formaPagamento.getDescricao() + " foi deletada com sucesso.");
                loadTable();
                clearAll();
            }
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        clearAll();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void tbFormaPagamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbFormaPagamentoMouseClicked
        // Método para selecionar um registro da tabela e carregar os campos
        int linha = tbFormaPagamento.getSelectedRow();
        int coluna = tbFormaPagamento.getSelectedColumn();

        if (linha >= 0) {
            existeSelecionado = true;

            FormaPagamentoDAO fpDao = new FormaPagamentoDAO();
            FormaPagamento formaPagamento = new FormaPagamento();
            long idSelecionado = Long.parseLong(tbFormaPagamento.getValueAt(linha, 0).toString());

            formaPagamento = fpDao.findById(idSelecionado);

            // setando valores nos campos do formulário
            tfCodigo.setText(String.valueOf(formaPagamento.getId()));
            tfDescricao.setText(formaPagamento.getDescricao());
        } else {
            existeSelecionado = false;
        }
    }//GEN-LAST:event_tbFormaPagamentoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPagamentos().setVisible(true);
            }
        });
    }

    public void configureLayout() {
        configureTableStyle();
        clearAll();
        loadTable();
    }

    public void loadTable() {
        // Método responsável em carregar os dados da tabela de pagamentos

        // Configurando o modelo da tabela
        DefaultTableModel modeloTabela = (DefaultTableModel) tbFormaPagamento.getModel();
        modeloTabela.setNumRows(0);

        // Carregando os dados do banco
        FormaPagamentoDAO fpDao = new FormaPagamentoDAO();
        List<FormaPagamento> lista = new ArrayList<>();
        lista = fpDao.getList();

        // Adicionando as linhas da tabella
        List<Object> dados;

        fpDao.getList().stream().forEach((fp) -> {
            modeloTabela.addRow(new Object[]{
                fp.getId(),
                fp.getDescricao()
            });
        });
    }

    public void configureTableStyle() {
        // Configurando o modelo da tabela
        DefaultTableModel modeloTabela = (DefaultTableModel) tbFormaPagamento.getModel();
        tbFormaPagamento.setRowSorter(new TableRowSorter(modeloTabela));

        // Centralizando informações
        DefaultTableCellRenderer tableCellRenderer = (DefaultTableCellRenderer) tbFormaPagamento.getDefaultRenderer(Object.class);
        tableCellRenderer.setHorizontalAlignment(SwingConstants.CENTER);
    }

    public void clearAll() {
        // Método responsável com a limpeza de todos os campos do formulário
        tfCodigo.setText("");
        tfDescricao.setText("");

        existeSelecionado = false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbFormaPagamento;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfDescricao;
    // End of variables declaration//GEN-END:variables
}
