-- MySQL Script generated by MySQL Workbench
-- 06/12/19 00:29:16
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema estoque
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema estoque
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `estoque` DEFAULT CHARACTER SET utf8 ;
USE `estoque` ;

-- -----------------------------------------------------
-- Table `estoque`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estoque`.`cliente` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `endereco` VARCHAR(200) NOT NULL,
  `nome` VARCHAR(200) NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `estoque`.`estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estoque`.`estoque` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `qtdMinima` INT(11) NOT NULL,
  `valorTotal` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `estoque`.`formapagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estoque`.`formapagamento` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `estoque`.`filial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estoque`.`filial` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `cpnj` VARCHAR(18) NOT NULL,
  `nome` VARCHAR(200) NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  `estoque_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_h7bydouhekjeqsne0qpj2rdva` (`estoque_id` ASC),
  CONSTRAINT `FK_h7bydouhekjeqsne0qpj2rdva`
    FOREIGN KEY (`estoque_id`)
    REFERENCES `estoque`.`estoque` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `estoque`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estoque`.`usuario` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_73l619d30rt4w3wvgnu7oqot3` (`nome` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `estoque`.`pedidoestoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estoque`.`pedidoestoque` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `observacao` VARCHAR(300) NOT NULL,
  `tipoPedido` VARCHAR(255) NOT NULL,
  `cliente_id` BIGINT(20) NULL DEFAULT NULL,
  `filial_id` BIGINT(20) NULL DEFAULT NULL,
  `formaPagamento_id` BIGINT(20) NULL DEFAULT NULL,
  `usuario_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_27ysdrhr38a5kuylrhdca1x5g` (`cliente_id` ASC),
  INDEX `FK_49ip47l860umm93nr2lpn2kos` (`filial_id` ASC),
  INDEX `FK_488fragpkkdq6fd3e24hg2chb` (`formaPagamento_id` ASC),
  INDEX `FK_j7mygeys4nc2uvbajin7kjhxo` (`usuario_id` ASC),
  CONSTRAINT `FK_27ysdrhr38a5kuylrhdca1x5g`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `estoque`.`cliente` (`id`),
  CONSTRAINT `FK_488fragpkkdq6fd3e24hg2chb`
    FOREIGN KEY (`formaPagamento_id`)
    REFERENCES `estoque`.`formapagamento` (`id`),
  CONSTRAINT `FK_49ip47l860umm93nr2lpn2kos`
    FOREIGN KEY (`filial_id`)
    REFERENCES `estoque`.`filial` (`id`),
  CONSTRAINT `FK_j7mygeys4nc2uvbajin7kjhxo`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `estoque`.`usuario` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `estoque`.`estoque_pedidoestoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estoque`.`estoque_pedidoestoque` (
  `Estoque_id` BIGINT(20) NOT NULL,
  `pedidos_id` BIGINT(20) NOT NULL,
  UNIQUE INDEX `UK_6dew3d3t470jb7mc4uj39wqob` (`pedidos_id` ASC),
  INDEX `FK_kk2vcb07x5wyks5vdtg2qkfbm` (`Estoque_id` ASC),
  CONSTRAINT `FK_6dew3d3t470jb7mc4uj39wqob`
    FOREIGN KEY (`pedidos_id`)
    REFERENCES `estoque`.`pedidoestoque` (`id`),
  CONSTRAINT `FK_kk2vcb07x5wyks5vdtg2qkfbm`
    FOREIGN KEY (`Estoque_id`)
    REFERENCES `estoque`.`estoque` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `estoque`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estoque`.`produto` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(200) NOT NULL,
  `codigoBarras` VARCHAR(50) NOT NULL,
  `descricao` VARCHAR(200) NOT NULL,
  `precoCusto` DOUBLE NOT NULL,
  `precoVenda` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `estoque`.`estoque_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estoque`.`estoque_produto` (
  `Estoque_id` BIGINT(20) NOT NULL,
  `produtos_id` BIGINT(20) NOT NULL,
  UNIQUE INDEX `UK_qnb7hmxggmf5q240773xu05ei` (`produtos_id` ASC),
  INDEX `FK_o6w31s3c0jnff4p345hi27t68` (`Estoque_id` ASC),
  CONSTRAINT `FK_o6w31s3c0jnff4p345hi27t68`
    FOREIGN KEY (`Estoque_id`)
    REFERENCES `estoque`.`estoque` (`id`),
  CONSTRAINT `FK_qnb7hmxggmf5q240773xu05ei`
    FOREIGN KEY (`produtos_id`)
    REFERENCES `estoque`.`produto` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `estoque`.`itenspedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estoque`.`itenspedido` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `quantidade` INT(11) NOT NULL,
  `statusItem` INT(11) NOT NULL,
  `valorUnitario` DOUBLE NOT NULL,
  `produto_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_oxo5mhwro6ao7tstihf1igxf6` (`produto_id` ASC),
  CONSTRAINT `FK_oxo5mhwro6ao7tstihf1igxf6`
    FOREIGN KEY (`produto_id`)
    REFERENCES `estoque`.`produto` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `estoque`.`pedidoestoque_itenspedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estoque`.`pedidoestoque_itenspedido` (
  `PedidoEstoque_id` BIGINT(20) NOT NULL,
  `itensPedido_id` BIGINT(20) NOT NULL,
  UNIQUE INDEX `UK_6w8df4f1p71li3fle8ulremv2` (`itensPedido_id` ASC),
  INDEX `FK_4qjk32vuml12l8yi71arbk5gu` (`PedidoEstoque_id` ASC),
  CONSTRAINT `FK_4qjk32vuml12l8yi71arbk5gu`
    FOREIGN KEY (`PedidoEstoque_id`)
    REFERENCES `estoque`.`pedidoestoque` (`id`),
  CONSTRAINT `FK_6w8df4f1p71li3fle8ulremv2`
    FOREIGN KEY (`itensPedido_id`)
    REFERENCES `estoque`.`itenspedido` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
