-- MySQL Script generated by MySQL Workbench
-- 06/07/19 00:24:29
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema estoqueit
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema estoqueit
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `estoqueit` DEFAULT CHARACTER SET utf8 ;
USE `estoqueit` ;

-- -----------------------------------------------------
-- Table `estoqueit`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estoqueit`.`categoria` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `estoqueit`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estoqueit`.`cliente` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `bairro` VARCHAR(200) NULL DEFAULT NULL,
  `cep` VARCHAR(9) NULL DEFAULT NULL,
  `cidade` VARCHAR(200) NULL DEFAULT NULL,
  `endereco` VARCHAR(300) NULL DEFAULT NULL,
  `uf` VARCHAR(2) NULL DEFAULT NULL,
  `nome` VARCHAR(200) NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `estoqueit`.`estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estoqueit`.`estoque` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `qtdMinima` INT(11) NOT NULL,
  `valorTotal` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `estoqueit`.`produtoestoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estoqueit`.`produtoestoque` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `produto` TINYBLOB NULL DEFAULT NULL,
  `qtdProduto` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `estoqueit`.`estoque_produtoestoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estoqueit`.`estoque_produtoestoque` (
  `Estoque_id` BIGINT(20) NOT NULL,
  `produtos_id` BIGINT(20) NOT NULL,
  UNIQUE INDEX `UK_bwnh676o6gw25gfs42alvw0ia` (`produtos_id` ASC),
  INDEX `FK_h0xmcw2c6yfxmidio3y2cmeq1` (`Estoque_id` ASC),
  CONSTRAINT `FK_bwnh676o6gw25gfs42alvw0ia`
    FOREIGN KEY (`produtos_id`)
    REFERENCES `estoqueit`.`produtoestoque` (`id`),
  CONSTRAINT `FK_h0xmcw2c6yfxmidio3y2cmeq1`
    FOREIGN KEY (`Estoque_id`)
    REFERENCES `estoqueit`.`estoque` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `estoqueit`.`filial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estoqueit`.`filial` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `cpnj` VARCHAR(18) NOT NULL,
  `nome` VARCHAR(200) NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  `estoque_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_h7bydouhekjeqsne0qpj2rdva` (`estoque_id` ASC),
  CONSTRAINT `FK_h7bydouhekjeqsne0qpj2rdva`
    FOREIGN KEY (`estoque_id`)
    REFERENCES `estoqueit`.`estoque` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `estoqueit`.`formapagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estoqueit`.`formapagamento` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `estoqueit`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estoqueit`.`produto` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `codigoBarras` VARCHAR(50) NOT NULL,
  `descricao` VARCHAR(200) NOT NULL,
  `precoCusto` DOUBLE NOT NULL,
  `precoVenda` DOUBLE NOT NULL,
  `categoria_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_7roeds87qp6pp2g07rv86t8cb` (`categoria_id` ASC),
  CONSTRAINT `FK_7roeds87qp6pp2g07rv86t8cb`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `estoqueit`.`categoria` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `estoqueit`.`itenspedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estoqueit`.`itenspedido` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `quantidade` INT(11) NOT NULL,
  `statusItem` INT(11) NOT NULL,
  `valorUnitario` DOUBLE NOT NULL,
  `produto_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_oxo5mhwro6ao7tstihf1igxf6` (`produto_id` ASC),
  CONSTRAINT `FK_oxo5mhwro6ao7tstihf1igxf6`
    FOREIGN KEY (`produto_id`)
    REFERENCES `estoqueit`.`produto` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `estoqueit`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estoqueit`.`usuario` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_73l619d30rt4w3wvgnu7oqot3` (`nome` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `estoqueit`.`pedidoestoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estoqueit`.`pedidoestoque` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `observacao` VARCHAR(300) NOT NULL,
  `tipoPedido` VARCHAR(255) NOT NULL,
  `cliente_id` BIGINT(20) NULL DEFAULT NULL,
  `filial_id` BIGINT(20) NULL DEFAULT NULL,
  `usuario_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_27ysdrhr38a5kuylrhdca1x5g` (`cliente_id` ASC),
  INDEX `FK_49ip47l860umm93nr2lpn2kos` (`filial_id` ASC),
  INDEX `FK_j7mygeys4nc2uvbajin7kjhxo` (`usuario_id` ASC),
  CONSTRAINT `FK_27ysdrhr38a5kuylrhdca1x5g`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `estoqueit`.`cliente` (`id`),
  CONSTRAINT `FK_49ip47l860umm93nr2lpn2kos`
    FOREIGN KEY (`filial_id`)
    REFERENCES `estoqueit`.`filial` (`id`),
  CONSTRAINT `FK_j7mygeys4nc2uvbajin7kjhxo`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `estoqueit`.`usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `estoqueit`.`pedidoestoque_itenspedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estoqueit`.`pedidoestoque_itenspedido` (
  `PedidoEstoque_id` BIGINT(20) NOT NULL,
  `itensPedido_id` BIGINT(20) NOT NULL,
  UNIQUE INDEX `UK_6w8df4f1p71li3fle8ulremv2` (`itensPedido_id` ASC),
  INDEX `FK_4qjk32vuml12l8yi71arbk5gu` (`PedidoEstoque_id` ASC),
  CONSTRAINT `FK_4qjk32vuml12l8yi71arbk5gu`
    FOREIGN KEY (`PedidoEstoque_id`)
    REFERENCES `estoqueit`.`pedidoestoque` (`id`),
  CONSTRAINT `FK_6w8df4f1p71li3fle8ulremv2`
    FOREIGN KEY (`itensPedido_id`)
    REFERENCES `estoqueit`.`itenspedido` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
